__name__ = "eyws"
__version__ = "1.0.0b3"
__author__ = "Can Elmas"
__email__ = "canelm@gmail.com"
__license__ = "Apache License 2.0"
__description__ = "Alternate AWS CLI"
__url__ = "https://github.com/canelmas/eyws"
